### ISSUE TITLE
ofSavePrettyJson

### ISSUE THREAD

**Issue by stephanschulz** [roymacdonald/ofxLineaDeTiempo#10]
I tried using `ofSavePrettyJson()` instead of `ofSaveJson()` but the addon is not reacting to play commands after loading the new json file.

FYI :)

**Comment by stephanschulz** [comment]
mh. maybe it's something else.
I have this json file from an earlier version of your addon (the one that crashed when trying to delete a keyframe) and now updated to the current version.
Somehow the json prevents the timeline from playing.
https://www.dropbox.com/s/2tynw3id71a52eu/timelineData.json?dl=0

**Comment by roymacdonald** [comment]
this is so odd.
how did you solve it?

**Comment by stephanschulz** [comment]
I had a stray pause() call :(
FYI  `ofSavePrettyJson()` does actually work.
How do I get the zoom + scroll bars to load in fully zoomed out state?
Right now the X axis is pretty zoomed in every time I start the app.

**Comment by roymacdonald** [comment]
I see.

> How do I get the zoom + scroll bars to load in fully zoomed out state?

`timeline.getPanel()->getTracksView()->getScrollbarH()->setValue({0,1});`

**Comment by roymacdonald** [comment]
BTW, I need to add a lot of handy functions to the timeline class, that call this, isntead of having to dig into the classes
