### ISSUE TITLE
sending ofParameter<void>

### ISSUE THREAD

**Issue by stephanschulz** [roymacdonald/ofxLineaDeTiempo#13]
i am trying to send a ofParameter<void> button event but it seems to not be detected on the receiver end. i see it was part of your todo list. does this work yet or am i doing something wrong?

**Comment by stephanschulz** [comment]
as a test i checked if `oscParametersReceiverExample` and `oscParametersSenderExample` work using `void` but they also do not send it; neither OF0.11.2 nor of_v20220530_osx_release. 
so it's either OF or the fact that i am on macOS 12.6 with an ARM chipset.

**Comment by roymacdonald** [comment]
The ofParameter<void> triggers work well on this addon. Not being able to send is an OF issue.
