### ISSUE TITLE
looping

### ISSUE THREAD

**Issue by stephanschulz** [roymacdonald/ofxLineaDeTiempo#2]
Hey Roy.

It's so great to have a timeline tool again for OF. Thank you.

How would I enable auto looping when ever the timeline reaches the end?

**Comment by roymacdonald** [comment]
Hi Stephan. 
Thanks. :)
You can enable looping through the GUI, there is a button at the top right of the timeline interface with an L which toggles looping. Check the screenshot below.
![Screen Shot 2020-07-27 at 15 29 32](https://user-images.githubusercontent.com/974878/88583302-16e62800-d01e-11ea-8b3a-1319a08b5a72.png)

Or you can set it programatically by `timeline.getTimeControl()->setLooping(true);`
cheers
