### ISSUE TITLE
How to set a new key point through the timeline interface?

### ISSUE THREAD

**Issue by stephanschulz** [roymacdonald/ofxLineaDeTiempo#3]
How to set a new key point through the timeline interface?

When I move the timeline play head either manually or because of hitting the play button, how do I know create a new key point for any of the GUI elements?

I know I can do a two finger click on the timeline. 
But this needs to be done slightly beside the timeline header line and then moved back in to position.

Is there a way to auto set a keypoint at the play head position of the gui that gets manually changed?

**Comment by stephanschulz** [comment]
and along the same lines, how do I delete a keypoint?

**Comment by roymacdonald** [comment]
There is still no automatic way for adding keyframes when changing a parameter, although it is in the top of the TODOs.
It can be done by adding a listener to a parameter and then adding the keyframe in the listener callback but it is a bit cumbersome. I think it is easier if I just add this feature.

To delete just select a keyframe and press the backspace key.

**Comment by roymacdonald** [comment]
Hi, no, there is not such thing! I was asked already for that feature, and I'll implement it soon.
On the meanwhile you can

**Comment by stephanschulz** [comment]
here a video showing how the app crashes when deleting (maybe the last) keypoint.
https://www.dropbox.com/s/hqqlth7drdjfy4p/keypoint_delete_crash.mov?dl=0

**Comment by roymacdonald** [comment]
I've seen this randomly happening . I'll try to recreate it, I think I know what the problem is.
Thanks for the video
