### ISSUE TITLE
how to set the duration

### ISSUE THREAD

**Issue by stephanschulz** [roymacdonald/ofxLineaDeTiempo#5]
I tried to set the timeline total duration with `timeline.getTimeControl()->setTotalTime(60);` but it still only ran for 10 seconds.

also.
when I zoom out view the bottom scroll bar handles, is there a way to jump back to the current play time?

thanks again for your help.

**Comment by roymacdonald** [comment]
`timeline.getTimeControl()->setTotalTime(60);`
That's not working. not updating the gui. I will check right now.
there is a shortcut though, `timeline.setTotalTime(60);` which does the same. Notice although that the passed values is in milliseconds.
If you zoom in or out or anything that changes the current timeline it should update to show the updated duration

**Comment by stephanschulz** [comment]
I notice that while `timeline.setTotalTime(30000)` does set the duration to 30 seconds, the top timeline header ruler still shows a duration of 8 seconds. It's not a big issue.
Also notices that when playhead passes some key points the gui element does not always seem to change to that settings.

<img width="1025" alt="Screen Shot 2020-07-28 at 12 08 29 PM" src="https://user-images.githubusercontent.com/1054816/88691947-7e0de600-d0cb-11ea-9a6f-0fa91cb54861.png">

**Comment by roymacdonald** [comment]
Thanks. This is because it needs to update the view. I am working on it. On the meanwhile, if you zoom with the zoom bar it will update the view and show it properly.
