### ISSUE TITLE
playhead invisible

### ISSUE THREAD

**Issue by stephanschulz** [roymacdonald/ofxLineaDeTiempo#7]
Hey Roy.
Sorry about blasting you with all those issues. It's in no way meant negatively; just a record of what I see.

Here you see that the play head does not appear no matter which button I press.
https://www.dropbox.com/s/9ltubvo7gu9pqj3/playhead_invisible.mov?dl=0

**Comment by roymacdonald** [comment]
Hi stephan,
don't be sorry. I appreciate a lot your feedback. It is super valuable. Thanks.
I have not seen such thing. although what keeps bogging me is that you are not seeing the time subdivisions in the upper bar, as those should be rendered always. actually the top time bar is where the playhead belongs to and where it gets rendered, as well as all the time to pixels conversions are in charge of the top time bar, so if it is not rendering for some reason, then that can what's causing a lot of the issues you get but I do not.
I understand that you are up to date with this repo. can you fully clean the project (in Xcode is in Product menu --> clean, and then again but pressing the alt key, it will be shown as Product menu --> Clean build folder...) and then rebuild ? does it still happen. 
Then can you run the app in verbose mode and paste here what you get in the console?
Last, which version of OF are you using? I am up to date with the current master, although I think this shouldn't be a big issue.

**Comment by stephanschulz** [comment]
I am on macOS 10.14.6 with OF0.11.0 and Xcode 10.3 

nothing really changed after doing both those cleans.
https://www.dropbox.com/s/dn5raowe4tlcjey/afterClean.mov?dl=0
here my app:
https://www.dropbox.com/s/u23rg1mrvbeec02/oscGuiTimeline.zip?dl=0

nothing printed in the console when using `ofSetLogLevel(OF_LOG_VERBOSE);`.
`2020-07-28 12:52:47.880530-0400 oscGuiTimelineDebug[35503:1373757] MessageTracer: load_domain_whitelist_search_tree:73: Search tree file's format version number (0) is not supported
2020-07-28 12:52:47.880598-0400 oscGuiTimelineDebug[35503:1373757] MessageTracer: Falling back to default whitelist
[notice ] ofApp: done gui_main setup

TracksPanelController::destroyView()
`

**Comment by roymacdonald** [comment]
Thanks. I'll check and let you know.

**Comment by roymacdonald** [comment]
Ok. So I've checked your app and I see whats going on. 
When setting the total time the timeline needs to update the view in order to show the correct stuff although it is not doing so. I am fixing it. The track region length should be saved but it seems as it is not. I'll double check that too.

**Comment by roymacdonald** [comment]
Although I can see the playhead
